version: '3.8'

services:
  db:
    image: jc21/mariadb-aria:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_USER}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db:/var/lib/mysql
  app:
    image: nextcloud
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_DATABASE: '${DB_USER}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_HOST: db
      NEXTCLOUD_ADMIN_USER: '${DB_USER}'
      NEXTCLOUD_ADMIN_PASSWORD: '${DB_PASSWORD}'
      NEXTCLOUD_TRUSTED_DOMAINS: '${NEXTCLOUD_TRUSTED_DOMAINS}'
    links:
      - db
 
volumes:
  db:
  nextcloud:
