version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_DB='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'
    ports:
      - 127.0.0.1:5432:5432

  nextcloud:
    image: nextcloud:fpm
    restart: always
    links:
      - postgres
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_DB='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'
      - POSTGRES_HOST=postgres
    ports: 
      - 127.0.0.1:8080:80

volumes:
  postgres:
  nextcloud:
